//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pim_scrap_query
    {
        public string ID { get; set; }
        public string FACLWP { get; set; }
        public string TOYNWP { get; set; }
        public string PARTWP { get; set; }
        public string DESXIT { get; set; }
        public string PLANIT { get; set; }
        public Nullable<double> BASPIT { get; set; }
        public Nullable<double> SCRMWP { get; set; }
        public string COMMIT_ { get; set; }
        public string TOY_NUMBER { get; set; }
        public string DESCRIPTION_ { get; set; }
        public Nullable<double> PRICE_ { get; set; }
        public Nullable<System.DateTime> DATE_INPUT { get; set; }
    }
}
