//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pim_scrap_old
    {
        public long id { get; set; }
        public Nullable<int> shift_ { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public string partnumber { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> pim_area_code { get; set; }
        public string pim_area_name { get; set; }
        public Nullable<int> pim_s_number { get; set; }
        public string pim_scap_code { get; set; }
        public string check_ { get; set; }
    }
}
