//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMSEntitiesScrap2 : DbContext
    {
        public MMSEntitiesScrap2()
            : base("name=MMSEntitiesScrap2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pim_scrap_query> pim_scrap_query { get; set; }
        public virtual DbSet<pim_scrap_code> pim_scrap_code { get; set; }
        public virtual DbSet<pim_scrap_num> pim_scrap_num { get; set; }
        public virtual DbSet<VO_SCRAP> VO_SCRAP { get; set; }
        public virtual DbSet<pim_scrap> pim_scrap { get; set; }
    }
}
