//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masbroEntitiesPIM : DbContext
    {
        public masbroEntitiesPIM()
            : base("name=masbroEntitiesPIM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pim_downtime> pim_downtime { get; set; }
        public virtual DbSet<pim_reject> pim_reject { get; set; }
        public virtual DbSet<PIM_SSC_CALCULATION> PIM_SSC_CALCULATION { get; set; }
        public virtual DbSet<PIM_SSC_MAIN> PIM_SSC_MAIN { get; set; }
        public virtual DbSet<PIM_SSC_O_DOWNTIME> PIM_SSC_O_DOWNTIME { get; set; }
        public virtual DbSet<PIM_SSC_O_REJECT> PIM_SSC_O_REJECT { get; set; }
        public virtual DbSet<PIM_SSC_OUTPUT> PIM_SSC_OUTPUT { get; set; }
        public virtual DbSet<pim_user_kpk> pim_user_kpk { get; set; }
        public virtual DbSet<pim_kpi_performance> pim_kpi_performance { get; set; }
        public virtual DbSet<pim_partnumber_notvalid> pim_partnumber_notvalid { get; set; }
        public virtual DbSet<VO_DOWNTIME> VO_DOWNTIME { get; set; }
        public virtual DbSet<VO_MAIN_CALC> VO_MAIN_CALC { get; set; }
        public virtual DbSet<VO_REJECT_PP> VO_REJECT_PP { get; set; }
        public virtual DbSet<VO_REJECT> VO_REJECT { get; set; }
        public virtual DbSet<VO_SCRAP> VO_SCRAP { get; set; }
        public virtual DbSet<pim_part_number_list> pim_part_number_list { get; set; }
    }
}
