//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PA_DOWNTIME_
    {
        public long downtime_id { get; set; }
        public Nullable<long> main_id_dt { get; set; }
        public string no_index { get; set; }
        public string pn { get; set; }
        public Nullable<System.DateTime> we_ { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public Nullable<int> shift_ { get; set; }
        public Nullable<int> pn_stdoutput { get; set; }
        public Nullable<int> total_output_pcs { get; set; }
        public Nullable<int> hour_counter { get; set; }
        public Nullable<System.TimeSpan> dt_start { get; set; }
        public Nullable<System.TimeSpan> dt_finish { get; set; }
        public Nullable<int> duration_minutes { get; set; }
        public Nullable<int> downtime_code { get; set; }
        public string DT_REMARKS { get; set; }
        public string DT_TYPE { get; set; }
        public string downtime_notes { get; set; }
        public string op_kpk { get; set; }
        public string op_name { get; set; }
    }
}
