//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_pim_output_reject
    {
        public long id { get; set; }
        public Nullable<int> rj_quantity { get; set; }
        public string rj_code { get; set; }
        public string rj_notes { get; set; }
        public string rj_remarks { get; set; }
        public Nullable<int> shift { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string op_kpk { get; set; }
        public string op_name { get; set; }
        public string no_machine { get; set; }
        public string partnumber { get; set; }
        public Nullable<int> shiftly_target { get; set; }
        public Nullable<int> actual_output { get; set; }
        public long id_user { get; set; }
        public Nullable<int> actual_good_output { get; set; }
        public Nullable<decimal> rj_rate2 { get; set; }
        public Nullable<long> main_id { get; set; }
        public string we_ { get; set; }
        public Nullable<int> mc_area { get; set; }
    }
}
