//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VO_DOWNTIME
    {
        public long downtime_id { get; set; }
        public Nullable<long> main_id_dt { get; set; }
        public Nullable<int> mc_area { get; set; }
        public string no_machine { get; set; }
        public string partnumber { get; set; }
        public string mold { get; set; }
        public string we_ { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public Nullable<int> shift_ { get; set; }
        public Nullable<int> pn_stdoutput { get; set; }
        public Nullable<int> total_output_pcs { get; set; }
        public Nullable<long> hour_counter { get; set; }
        public Nullable<int> total_actoutput { get; set; }
        public Nullable<System.TimeSpan> dt_start { get; set; }
        public Nullable<System.TimeSpan> dt_finish { get; set; }
        public Nullable<int> duration_minutes { get; set; }
        public string downtime_code { get; set; }
        public string dt_remarks { get; set; }
        public string dt_type { get; set; }
        public string downtime_notes { get; set; }
        public string op_kpk { get; set; }
        public string op_name { get; set; }
    }
}
