//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pim_part_number_list
    {
        public long ID { get; set; }
        public string PART { get; set; }
        public string DESC { get; set; }
        public string MOLD { get; set; }
        public Nullable<int> FAMILY { get; set; }
        public Nullable<int> CAVITY { get; set; }
        public Nullable<int> CT { get; set; }
        public Nullable<double> MCHRS { get; set; }
        public string PN_COLORANT { get; set; }
        public string COLOR { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<System.DateTime> DATE_INPUT { get; set; }
    }
}
