//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIM_SSC_CALCULATION
    {
        public long totalcalc_id { get; set; }
        public Nullable<long> main_id_tc { get; set; }
        public Nullable<int> total_output_pcs { get; set; }
        public Nullable<int> total_good_output { get; set; }
        public Nullable<int> pn_stdoutput { get; set; }
        public Nullable<int> totalRJ { get; set; }
        public Nullable<int> totalNotRun { get; set; }
        public Nullable<int> totalDT { get; set; }
        public Nullable<int> total_time { get; set; }
        public Nullable<int> pn_operatingtime { get; set; }
    
        public virtual PIM_SSC_MAIN PIM_SSC_MAIN { get; set; }
    }
}
