//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pim_partnumber_notvalid
    {
        public long ID { get; set; }
        public Nullable<int> shift { get; set; }
        public string no_machine { get; set; }
        public Nullable<System.DateTime> date_input { get; set; }
        public string partnumber_not_valid { get; set; }
    }
}
