//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pim_oee
    {
        public long id { get; set; }
        public Nullable<long> main_id { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public string we { get; set; }
        public string machine { get; set; }
        public Nullable<int> shift { get; set; }
        public Nullable<decimal> total_time { get; set; }
        public Nullable<decimal> break_ { get; set; }
        public Nullable<decimal> briefing_ { get; set; }
        public Nullable<decimal> available_time { get; set; }
        public Nullable<decimal> not_running { get; set; }
        public Nullable<decimal> total_breakdowntime { get; set; }
        public Nullable<decimal> operating_time { get; set; }
        public Nullable<int> cycle_time { get; set; }
        public Nullable<int> standard_output { get; set; }
        public Nullable<int> actual_output { get; set; }
        public Nullable<int> reject { get; set; }
        public Nullable<int> good_output { get; set; }
        public Nullable<int> var { get; set; }
        public Nullable<decimal> availability { get; set; }
        public Nullable<decimal> performance { get; set; }
        public Nullable<decimal> quality { get; set; }
        public Nullable<decimal> oee { get; set; }
    }
}
