//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIM_SSC_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIM_SSC_MAIN()
        {
            this.PIM_SSC_CALCULATION = new HashSet<PIM_SSC_CALCULATION>();
            this.PIM_SSC_O_DOWNTIME = new HashSet<PIM_SSC_O_DOWNTIME>();
            this.PIM_SSC_O_REJECT = new HashSet<PIM_SSC_O_REJECT>();
            this.PIM_SSC_OUTPUT = new HashSet<PIM_SSC_OUTPUT>();
        }
    
        public long main_id { get; set; }
        public string partnumber { get; set; }
        public string mold { get; set; }
        public Nullable<int> shift_ { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public string we_ { get; set; }
        public string op_kpk { get; set; }
        public string op_name { get; set; }
        public string no_machine { get; set; }
        public Nullable<int> mc_area { get; set; }
        public Nullable<int> sch { get; set; }
        public Nullable<int> total_actoutput { get; set; }
        public Nullable<int> pn_ct { get; set; }
        public Nullable<int> pn_cav { get; set; }
        public Nullable<int> pn_set { get; set; }
        public Nullable<int> pengalioutput { get; set; }
        public string pn_notes { get; set; }
        public string part_pp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIM_SSC_CALCULATION> PIM_SSC_CALCULATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIM_SSC_O_DOWNTIME> PIM_SSC_O_DOWNTIME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIM_SSC_O_REJECT> PIM_SSC_O_REJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIM_SSC_OUTPUT> PIM_SSC_OUTPUT { get; set; }
    }
}
