//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE_SSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIM_SSC_O_REJECT
    {
        public long reject_id { get; set; }
        public Nullable<long> hour_counter { get; set; }
        public Nullable<long> main_id_rj { get; set; }
        public Nullable<int> reject_qty { get; set; }
        public string reject_code { get; set; }
        public string reject_notes { get; set; }
    
        public virtual pim_reject pim_reject { get; set; }
        public virtual PIM_SSC_MAIN PIM_SSC_MAIN { get; set; }
    }
}
